version: 2

project_name: circleci

before:
  hooks:
    - go mod tidy

builds:
  - id: circleci
    main: ./cmd/circleci
    binary: circleci
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
    ignore:
      - goos: windows
        goarch: arm64
        goarm: "6"
    ldflags:
      - -s -w
      - -X main.buildVersion={{.Version}}
      - -X main.buildDate={{.Date}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
